import os
from flask import Flask, request, jsonify
import requests
from bs4 import BeautifulSoup
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from flask_cors import CORS

app = Flask(__name__, static_folder='static', static_url_path='')
CORS(app)

@app.route('/')
def index():
    """
    Serves the index.html file from the 'static' folder at the root URL.
    """
    return app.send_static_file('index.html')

def scrape_page(url):
    """
    Fetches the URL and extracts text from all <p> tags.
    """
    try:
        response = requests.get(url)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, "html.parser")
        paragraphs = soup.find_all('p')
        page_text = " ".join(p.get_text() for p in paragraphs)
        return page_text.strip()
    except Exception as e:
        print(f"Error scraping {url}: {e}")
        return ""

# List of UMA pages to scrape
urls = [
    "https://uma.edu.pe/",
    "https://uma.edu.pe/admision/",
    "https://uma.edu.pe/proyectos-de-investigacion/",
    "https://uma.edu.pe/uma-barrio/",
    "https://uma.edu.pe/alumni/",
    "https://uma.edu.pe/docentes/",
    "https://uma.edu.pe/oficina-de-gestion-docente/",
    "https://bibliovirtual.uma.edu.pe/based.html",
    "https://uma.edu.pe/dici-uma/",
    "https://uma.edu.pe/contactos/",
    "https://uma.edu.pe/curso-ia40/",
    "https://uma.edu.pe/uma-solar/",
    "https://uma.edu.pe/proyecto-suma/",
    "https://uma.edu.pe/voluntariado/",
    "https://uma.edu.pe/postula-aqui/",
    "https://uma.edu.pe/expoferia-virtual-uma-exhibira-productos-de-emprendedores/",
"https://uma.edu.pe/uma-lanza-cursos-cortos-para-emprendedores-y-mipymes/",
"https://uma.edu.pe/uma-anuncia-el-lanzamiento-de-uma-barrio/",
"https://uma.edu.pe/22-oct-uma-10-anos-10-momentos-que-marcaron-nuestra-historia/",
"https://uma.edu.pe/uma-realizo-congreso-internacional-de-investigacion/",
"https://uma.edu.pe/uma-realizo-con-exito-el-expo-emprendedor-2021/",
"https://uma.edu.pe/20-oct-la-responsabilidad-social-universitaria-la-calidad-educativa-y-la-internacionalizacion/",
"https://uma.edu.pe/innovative-scale-canada-abre-convocatoria-de-asesorias-a-emprendedores-uma/",
"https://uma.edu.pe/14-15-oct-ciuma-2021/",
"https://uma.edu.pe/mejorando-mis-finanzas-personales/",
"https://uma.edu.pe/el-marketing-emocional-tres-bases-para-una-estrategia-de-exito/",
"https://uma.edu.pe/extraordinaria-conferencia-internacional-sobre-emprendimiento-y-marca-personal-se-realizo-en-la-uma/",
"https://uma.edu.pe/la-universidad-maria-auxiliadora-uma-firma-convenio-internacional-con-la-corporacion-universitaria-lasallista-ul/",
"https://uma.edu.pe/uma-apertura-su-maestria-en-salud-publica/",
"https://uma.edu.pe/5-oct-conferencia-emprendimiento-la-teoria-del-fracaso/",
"https://uma.edu.pe/uma-realizara-congreso-internacional-de-ciencias-empresariales/",
"https://uma.edu.pe/30-set-congreso-internacional-de-ciencias-empresariales/",
"https://uma.edu.pe/dr-adesh-vora-canada-realiza-importante-ponencia-en-la-uma/",
"https://uma.edu.pe/la-uma-firma-convenio-internacional-con-la-universidad-cooperativa-de-colombia-ucc/",
"https://uma.edu.pe/rectora-de-la-uma-recibe-reconocimiento-por-parte-de-la-comision-de-educacion-juventud-y-deportes-del-congreso-de-la-republica/",
"https://uma.edu.pe/phd-rawi-abdelal-eeuu-imparte-trascendental-conferencia-sobre-el-capitalismo/",
"https://uma.edu.pe/23-set-webinar-emprendimiento-y-marca-personal/",
"https://uma.edu.pe/20-set-webinar-internacional-el-futuro-de-la-farmacia/",
"https://uma.edu.pe/escuela-de-enfermeria-de-la-uma-celebra-el-dia-del-enfermero-con-evento-internacional/",
"https://uma.edu.pe/uma-lanza-programa-semillero-internacional-con-universidades-de-colombia-y-brasil/",
"https://uma.edu.pe/escuela-de-enfermeria-de-la-uma-realiza-ceremonia-de-la-luz/",
"https://uma.edu.pe/15-set-webinar-internacional-la-crisis-del-capitalismo/",
"https://uma.edu.pe/directora-de-la-escuela-de-nutricion-de-la-uma-participara-en-congreso-internacional/",
"https://uma.edu.pe/uma-felicita-a-docentes-que-forman-parte-del-renacyt-tras-la-convocatoria-2021/",
"https://uma.edu.pe/el-dr-henry-castillo-colombia-imparte-destacadas-conferencias-internacionales-en-la-uma/",
"https://uma.edu.pe/3-agosto-webinar-internacional-desarrollando-una-personalidad-arrolladora-para-un-exito-profesional/",
"https://uma.edu.pe/2-agosto-webinar-internacional-psicologia-y-neurociencia-una-alianza-definitiva-para-el-futuro-de-la-salud-y-el-bienestar/",
"https://uma.edu.pe/estudiantes-y-docentes-de-la-uma-registran-7-patentes-industriales-ante-indecopi/",
"https://uma.edu.pe/oportunidades-para-emprender-en-el-sector-salud/",
"https://uma.edu.pe/los-riesgos-asociados-a-la-auditoria/",
"https://uma.edu.pe/los-cambios-del-marketing-contextual/",
"https://uma.edu.pe/el-podcast-como-herramienta-de-comunicacion-y-marketing/",
"https://uma.edu.pe/la-pandemia-y-las-ventas/",
"https://uma.edu.pe/mi-nombre-mi-marca-5-claves-para-desarrollar-tu-marca-personal/",
"https://uma.edu.pe/la-revista-agora-ahora-esta-indizada-a-latindex-2-0/",
"https://uma.edu.pe/salvador-carlucci-ponente-norteamericano-imparte-conferencia-sobre-tecnologia-en-salud-para-los-alumnos-de-la-uma/",
"https://uma.edu.pe/22-mayo-webinar-liderazgo-trascendente-y-motivacional/",
"https://uma.edu.pe/la-universidad-maria-auxiliadora-ofrecera-su-maestria-en-salud-publica/",
"https://uma.edu.pe/la-importancia-de-la-investigacion-de-mercados-en-el-emprendimiento/",
"https://uma.edu.pe/foodturo-cual-es-el-futuro-del-sector-agrario/",
"https://uma.edu.pe/12-mayo-conferencia-internacional-el-futuro-de-la-tecnologia/",
"https://uma.edu.pe/el-rector-de-universidad-mexicana-imparte-conferencia-web-en-la-uma/",
"https://uma.edu.pe/6-7-mayo-jornada-internacional-de-investigacion/",
"https://uma.edu.pe/3-mayo-ii-feria-virtual-de-medicina-alternativa/",
"https://uma.edu.pe/19-abril-webinar-internacional-emprendimiento-sostenible/",
"https://uma.edu.pe/17-abril-ceremonia-de-la-luz-e-imposicion-de-uniformes-para-enfermeria/",
"https://uma.edu.pe/25-marzo-webinar-incubadoras-de-negocios-importancia-en-el-ecosistema-emprendedor/",
"https://uma.edu.pe/cooperacion-academica-entre-la-uma-y-la-ucsh-de-chile/",
"https://uma.edu.pe/sunat-tarda-pero-llega/",
"https://uma.edu.pe/scrum-metodologias-agiles-y-por-que-ayudan-a-los-emprendedores/",
"https://uma.edu.pe/11-marzo-webinar-marketing-digital-para-la-micro-y-pequena-empresa/",
"https://uma.edu.pe/9-marzo-webinar-oxigenoterapia-con-canula-de-alto-flujo-en-pacientes-covid-19/",
"https://uma.edu.pe/7-marzo-webinar-manejo-perioperatorio-del-paciente-con-sars-cov-2-covid-19/",
"https://uma.edu.pe/6-marzo-webinar-startups-y-su-enfoque-en-la-innovacion/",
"https://uma.edu.pe/uma-lanza-emprende-uma-tv/",
"https://uma.edu.pe/uma-realizo-congreso-internacional-de-emprendimiento/",
"https://uma.edu.pe/28-feb-webinar-los-retos-y-la-pasion-que-mueven-a-los-enfermeros-en-tiempos-del-covid-19/",
"https://uma.edu.pe/26-27-feb-congreso-internacional-de-emprendimiento/",
"https://uma.edu.pe/13-feb-webinar-descubriendo-nuestras-capacidades-para-el-empleo/",
"https://uma.edu.pe/14-feb-webinar-eficacia-de-las-vacunas-covid-19/",
"https://uma.edu.pe/se-realiza-imposicion-de-uniformes-de-la-escuela-de-psicologia/",
"https://uma.edu.pe/13-feb-webinar-internacional-creatividad-e-innovacion-empresarial-en-tiempos-de-pandemia/",
"https://uma.edu.pe/8-febrero-webinar-ventilacion-mecanica-en-prono-del-paciente-covid/",
"https://uma.edu.pe/uma-realiza-ceremonia-de-investidura-a-los-internos-de-enfermeria/",
"https://uma.edu.pe/31-ene-webinar-liderazgo-en-enfermeria-en-tiempos-de-pandemia/",
"https://uma.edu.pe/28-ene-ceremonia-de-imposicion-de-uniforme-de-enfermeria/",
"https://uma.edu.pe/emprender-con-inteligencia-estrategica/",
"https://uma.edu.pe/cinco-claves-del-marketing-digital-para-tu-propio-negocio/",
"https://uma.edu.pe/la-segunda-independencia-latinoamericana-la-revolucion-de-las-patentes/",
"https://uma.edu.pe/negocios-internacionales-que-como-por-que-y-para-que/",
"https://uma.edu.pe/direccion-de-investigacion-de-la-uma-realiza-jornada-de-capacitacion-docente-en-investigacion/",
"https://uma.edu.pe/los-documentos-que-necesitas-tener-para-realizar-importaciones/",
"https://uma.edu.pe/27-ene-jornada-internacional-de-sexualidad/",
"https://uma.edu.pe/20-ene-uso-de-herramientas-informaticas-en-entornos-virtuales/",
"https://uma.edu.pe/20-ene-busqueda-de-informacion-y-uso-de-mendeley/",
"https://uma.edu.pe/se-busca-supervisor-de-produccion/",
"https://uma.edu.pe/20-ene-como-elaborar-un-consultorio-de-enfermeria/",
"https://uma.edu.pe/19-ene-webinar-redaccion-de-articulos-cientificos/",
"https://uma.edu.pe/19-ene-estadistica-aplicada-a-la-investigacion/",
"https://uma.edu.pe/uma-realiza-ceremonia-de-reconocimiento-y-felicitacion-para-los-docentes-que-han-realizado-publicaciones-cientificas-y-patente-durante-el-ano-2020/",
"https://uma.edu.pe/13-ene-como-ser-un-buen-tutor-en-entornos-virtuales/",
"https://uma.edu.pe/13-ene-ensenanza-por-competencias-en-entornos-virtuales/",
"https://uma.edu.pe/diferenciando-la-preocupacion-saludable-de-la-ansiedad-frente-al-covid-19/",
"https://uma.edu.pe/como-entender-y-sobrellevar-la-tristeza-y-depresion-durante-la-cuarentena/",
"https://uma.edu.pe/como-afrontar-la-ansiedad-frente-al-covid-19/",
"https://uma.edu.pe/uso-adecuado-de-la-informacion-sobre-el-covid-19/",
"https://uma.edu.pe/reflexiones-en-tiempo-de-crisis/",
"https://uma.edu.pe/se-busca-enfermeroa/",
"https://uma.edu.pe/7-enero-webinar-ventas-y-liderazgo/",
"https://uma.edu.pe/4-enero-webinar-por-que-estudiar-nutricion-y-dietetica/",
"https://uma.edu.pe/20-dic-webinar-una-mirada-al-covid-19-desde-la-atencion-primaria-en-espana/",
"https://uma.edu.pe/uma-celebro-su-ix-aniversario/",
"https://uma.edu.pe/17-dic-webinar-la-sunat-y-la-cultura-tributaria-en-el-peru/",
"https://uma.edu.pe/13-dic-taller-de-gasometria-interpretacion-practica-de-aga-en-enfermeria-en-un-minuto/",
"https://uma.edu.pe/docente-investigador-de-la-uma-publica-trabajo-realizado-junto-a-profesionales-del-csic-espana/",
"https://uma.edu.pe/11-dic-webinar-costos-en-una-empresa-transnacional/",
"https://uma.edu.pe/supervisor-de-produccion/",
"https://uma.edu.pe/se-busca-asistente-contable/",
"https://uma.edu.pe/asistente-de-materias-primas/",
"https://uma.edu.pe/presidente-del-conaic-mexico-impartira-clases-virtuales-a-docentes-de-la-uma/",
"https://uma.edu.pe/supervisor-de-desarrollo-analitico/",
"https://uma.edu.pe/gestion-del-estres-en-tiempos-de-pandemia-en-estudiantes-y-docentes-de-la-uma/",
"https://uma.edu.pe/impacto-del-covid-19-en-la-salud-alimentaria/",
"https://uma.edu.pe/anemia-en-tiempos-del-covid-19/",
"https://uma.edu.pe/docente-de-la-universidad-autonoma-de-barcelona-espana-impartira-cursos-a-docentes-de-la-uma/",
"https://uma.edu.pe/profesor-e-investigador-de-la-uma-participo-en-publicacion-espanola-sobre-la-educacion-superior-en-el-peru/",
"https://uma.edu.pe/uma-impartira-5-nuevos-programas-de-especializacion-en-enfermeria/",
"https://uma.edu.pe/uma-patenta-primera-cabina-de-desinfeccion-inclusiva-del-peru/",
"https://uma.edu.pe/uma-patenta-primera-cabina-de-desinfeccion-inclusiva-del-peru-que-funciona-con-energia-solar/",
"https://uma.edu.pe/6-junio-webinar-modelo-sir-para-entender-la-dinamica-del-covid-19/",
"https://uma.edu.pe/7-junio-webinar-estilos-de-vida-saludables-para-prevenir-problemas-psicosociales-en-tiempos-del-covid-19/",
"https://uma.edu.pe/13-junio-webinar-el-estado-de-la-enfermeria-en-el-mundo-como-una-hoja-de-ruta-para-las-inversiones/",
"https://uma.edu.pe/24-junio-webinar-participacion-de-los-nutricionistas-en-el-gobierno-local/",
"https://uma.edu.pe/13-junio-webinar-la-regulacion-emocional-y-el-distanciamiento-social/",
"https://uma.edu.pe/7-junio-webinar-como-afrontar-la-ansiedad-frente-al-covid-19/",
"https://uma.edu.pe/estudiantes-de-la-uma-escenifican-vida-y-obra-de-florence-nightingale/",
"https://uma.edu.pe/se-busca-enfermera/",
"https://uma.edu.pe/12-dic-capacitacion-herramientas-digitales-e-insercion-laboral/",
"https://uma.edu.pe/uma-cuenta-con-dos-nuevas-carreras-psicologia-y-nutricion/",
"https://uma.edu.pe/se-presento-la-primera-edicion-en-espanol-de-uno-de-los-libros-mas-influyentes-en-la-enfermeria-contemporanea-2/",
"https://uma.edu.pe/se-presento-la-primera-edicion-en-espanol-de-uno-de-los-libros-mas-influyentes-en-la-enfermeria-contemporanea/",
"https://uma.edu.pe/2-dic-obra-de-teatro-sobre-la-vida-de-florence-nightingale/",
"https://uma.edu.pe/gerente-general-de-la-uma-realiza-visita-academica-oficial-a-la-universidad-de-mujeres-de-texas/",
"https://uma.edu.pe/se-busca-asesor-de-creditos/",
"https://uma.edu.pe/la-universidad-maria-auxiliadora-da-bienvenida-a-la-dra-norma-cuellar/",
"https://uma.edu.pe/solicitan-practicantes-de-administracion/",
"https://uma.edu.pe/uma-otorga-becas-a-sus-estudiantes/",
"https://uma.edu.pe/dra-kathleen-sitzman-eeuu-realiza-talleres-vivenciales-en-la-uma/",
"https://uma.edu.pe/dra-kahtleen-sitzman-da-conferencia-en-el-colegio-de-enfermeros-del-peru-gracias-a-la-uma/",
"https://uma.edu.pe/docente-de-la-universidad-de-carolina-del-norte-visitara-por-segunda-vez-la-uma/",
"https://uma.edu.pe/alumos-de-la-uma-obtienen-primer-puesto-en-concurso-de-investigacion/",
"https://uma.edu.pe/ponente-de-la-universidad-autonoma-de-barcelona-realiza-conferencia-en-la-uma/",
"https://uma.edu.pe/delegacion-de-la-universidad-de-mujeres-de-texas-visita-la-uma-2/",
"https://uma.edu.pe/delegacion-de-la-universidad-de-mujeres-de-texas-visita-la-uma/",
"https://uma.edu.pe/alumnos-de-la-uma-llevan-ayuda-a-los-damnificados/",
"https://uma.edu.pe/docentes-y-estudiantes-de-la-universidad-de-mujeres-de-texas-visitaron-la-uma/",
"https://uma.edu.pe/alumnos-de-la-uma-realizan-campana-de-salud-integral-en-la-quebrada/",
"https://uma.edu.pe/cientos-de-ninos-disfrutaron-de-una-manana-llena-de-regalos/",
"https://uma.edu.pe/uma-firma-convenio-con-la-corporacion-universitaria-lasallista-colombia/",
"https://uma.edu.pe/se-busca-asistente-para-topico/",
"https://uma.edu.pe/se-busca-analista-de-control-de-calidad/",
"https://uma.edu.pe/concurso-publico-de-meritos-abiertos/",
"https://uma.edu.pe/se-necesita-asistente-de-comercio-exterior/",
"https://uma.edu.pe/se-busca-tecnico-en-farmacia/",
"https://uma.edu.pe/asistente-contable/",
"https://uma.edu.pe/asistente-de-registros-sanitarios-farmacias-peruanas/",
"https://uma.edu.pe/director-de-administracion/",
"https://uma.edu.pe/director-y-estudiantes-de-la-uma-participacion-en-evento-internacional-de-emprendimiento/",
"https://uma.edu.pe/31-mayo-charla-diplomado-en-asuntos-regulatorios-del-sector-farmaceutico/",
"https://uma.edu.pe/15-junio-conferencia-internacional-secuelas-del-covid-prolongado/",
"https://uma.edu.pe/uma-twu-mision-academica-conjunta-2022/",
"https://uma.edu.pe/02-junio-diplomado-asuntos-regulatorios-del-sector-farmaceutico/",
"https://uma.edu.pe/14-mayo-ceremonia-de-investidura-e-p-enfermeria/",
"https://uma.edu.pe/director-de-emprendimiento-de-la-uma-realizo-conferencia-magistral-para-la-universidad-mesoamericana-de-mexico/",
"https://uma.edu.pe/16-mayo-charla-informativa-sobre-el-diplomado-en-enfermedades-cronicas-no-transmisibles/",
"https://uma.edu.pe/9-mayo-12-mayo-iv-feria-de-medicina-alternativa/",
"https://uma.edu.pe/estudiantes-de-la-uma-fueron-entrevistados-por-el-chema-salcedo-en-pbo/",
"https://uma.edu.pe/texas-womans-university-twu-y-la-universidad-maria-auxiliadora-uma-en-mision-academica-conjunta/",
"https://uma.edu.pe/uma-da-la-bienvenida-a-sus-cachimbos-2022/",
"https://uma.edu.pe/dra-gladys-moran-rectora-de-la-uma-es-entrevistada-sobre-internacionalizacion/",
"https://uma.edu.pe/28-abril-congreso-de-emprendimiento-2022/",
"https://uma.edu.pe/la-universidad-maria-auxiliadora-uma-capacita-a-dirigentes-de-ollas-comunes-de-san-juan-de-lurigancho/",
"https://uma.edu.pe/jornada-de-psicologia-2022/",
"https://uma.edu.pe/congreso-internacional-de-emprendimiento-de-la-universidad-maria-auxiliadora-se-desarrollara-este-28-y-29-de-abril/",
"https://uma.edu.pe/la-universidad-maria-auxiliadora-uma-realiza-conferencia-internacional-de-emprendimiento-con-destacado-profesor-de-colombia/",
"https://uma.edu.pe/estudiantes-de-la-uma-culminan-con-exito-primera-parte-del-programa-naf/",
"https://uma.edu.pe/por-que-estudiar-enfermeria/",
"https://uma.edu.pe/22-abril-disenando-un-modelo-de-negocio/",
"https://uma.edu.pe/carreras-de-ciencias-empresariales/",
"https://uma.edu.pe/21-abril-pertinencia-del-pensamiento-administrativo-corporativo-en-el-emprendimiento/",
"https://uma.edu.pe/por-que-estudiar-nutricion-y-dietetica/",
"https://uma.edu.pe/por-que-estudiar-psicologia-2/",
"https://uma.edu.pe/por-que-estudiar-administracion-y-marketing/",
"https://uma.edu.pe/12-abril-charla-informativa/",
"https://uma.edu.pe/uma-talk-emprendimiento-de-productos-saludables-caso-conde-olivo/",
"https://uma.edu.pe/tu-bebe-empieza-a-comer-aprende-con-los-especialistas/",
"https://uma.edu.pe/por-que-estudiar-nutricion-y-dietetica-2/",
"https://uma.edu.pe/8-abril-el-rol-del-quimico-farmaceutico-en-la-sociedad-peruana/",
"https://uma.edu.pe/7-abril-crea-tu-producto-y-traspasa-fronteras/",
"https://uma.edu.pe/5-abril-quieres-ser-nutricionista/",
"https://uma.edu.pe/loncheras-saludables/",
"https://uma.edu.pe/descubre-los-beneficios-de-estudiar-administracion-y-contabilidad/",
"https://uma.edu.pe/el-rol-del-qf-en-la-sociedad-peruana/",
"https://uma.edu.pe/crea-tu-producto-y-traspasa-fronteras/",
"https://uma.edu.pe/por-que-estudiar-psicologia/",
"https://uma.edu.pe/uma-talks-importancia-de-los-sitios-web/",
"https://uma.edu.pe/por-que-estudiar-enfermeria-2/",
"https://uma.edu.pe/quieres-ser-nutricionista/",
"https://uma.edu.pe/por-que-estudiar-farmacia-y-bioquimica/",
"https://uma.edu.pe/uma-talks-transformacion-digital/",
"https://uma.edu.pe/universidad-maria-auxiliadora-uma-y-sunat-impartiran-programa-internacional-naf-a-sus-estudiantes/",
"https://uma.edu.pe/la-universidad-maria-auxiliadora-uma-junto-con-beyond-the-light-llevaron-energia-solar-a-18-viviendas-que-carecen-de-fluido-electrico/",
"https://uma.edu.pe/clases-espejo-en-maestria-de-la-uma/",
"https://uma.edu.pe/energia-solar-llegara-a-18-viviendas-que-carecen-de-fluido-electrico-gracias-a-uma/",
"https://uma.edu.pe/director-de-emprendimiento-e-innovacion-de-la-uma-participo-como-jurado-en-importante-final-de-concurso-nacional/",
"https://uma.edu.pe/marketing-y-ventas-en-tiempos-de-covid/",
"https://uma.edu.pe/5-claves-para-lanzar-podcasts-si-tienes-un-negocio-propio/",
"https://uma.edu.pe/8-marzo-conferencia-internacional-estrategia-creacion-de-valor-para-un-desempeno-excepcional/",
"https://uma.edu.pe/23-feb-reordenando-una-empresa-en-quiebra-en-tiempos-de-covid/",
"https://uma.edu.pe/16-febrero-uma-talks/",
"https://uma.edu.pe/5-marzo-inicio-de-clases/",
"https://uma.edu.pe/lanzamiento-de-los-uma-talks-sera-en-el-mes-de-febrero/",
"https://uma.edu.pe/7-febrero-charla-informativa/",
"https://uma.edu.pe/la-partida-doble-contable-cambio-el-mundo/",
"https://uma.edu.pe/gestion-de-contenidos-en-medios-digitales-branded-content-y-content-marketing/",
"https://uma.edu.pe/31-enero-maestria-en-salud-publica-conversatorio-politicas-publicas-preventivas/",
"https://uma.edu.pe/uma-reconoce-labor-de-sus-docentes-investigadores-durante-el-2021/",
"https://uma.edu.pe/20-enero-quieres-realizar-una-maestria-en-salud-publica-conversa-con-los-expertos/",
"https://uma.edu.pe/17-enero-ceremonia-de-reconocimiento-a-docentes-uma-por-los-logros-en-investigacion-2021/",
"https://uma.edu.pe/13-enero-charla-informativa-nutricion-y-dietetica/",
"https://uma.edu.pe/6-ene-quieres-ser-nutricionista-conversa-con-los-expertos/",
"https://uma.edu.pe/uma-realiza-conversatorio-retos-de-los-profesionales-en-salud-publica/",
"https://uma.edu.pe/uma-firma-convenio-con-la-universidad-san-buenaventura-colombia-seccional-cali/",
"https://uma.edu.pe/rectora-de-la-uma-realiza-visita-academica-a-usb-medellin/",
"https://uma.edu.pe/recursos-digitales-para-la-presentacion-de-informacion/",
"https://uma.edu.pe/la-industria-de-los-videojuegos-y-netflix/",
"https://uma.edu.pe/la-firma-convenio-con-la-universidad-san-buenaventura-de-colombia-sede-bogota/",
"https://uma.edu.pe/uma-formara-y-certificara-asesores-y-evaluadores-en-investigacion-cientifica/",
"https://uma.edu.pe/autoridades-de-la-uma-se-reunen-con-el-decano-nacional-del-colegio-de-psicologos-del-peru/",
"https://uma.edu.pe/dra-gladys-moran-paredes-rectora-de-la-uma-formo-parte-de-la-fundacion-de-la-catedra-mujer/",
"https://uma.edu.pe/conv-alianza-del-pacifico/",
"https://uma.edu.pe/convenio-universidad-de-jaen-espana/",
"https://uma.edu.pe/convenio-con-la-universidad-de-san-buenaventura-cali-colombia/",
"https://uma.edu.pe/convenio-con-la-universidad-de-san-buenaventura-bogota-colombia/",
"https://uma.edu.pe/convenio-universidad-de-san-buenaventura-medellin-colombia/",
"https://uma.edu.pe/convenio-fundacion-universitaria-maria-cano-colombia/",
"https://uma.edu.pe/convenio-corporacion-universitaria-lasallista-colombia/",
"https://uma.edu.pe/convenio-con-la-fundacion-universitaria-jorge-tadeo-lozano/",
"https://uma.edu.pe/11-julio-iniciativas-legislativas-para-la-salud-publica/",
"https://uma.edu.pe/11-julio-aprende-a-elaborar-alcohol-en-gel/",
"https://uma.edu.pe/08-julio-charla-informativa-ciencias-empresariales/",
"https://uma.edu.pe/06-julio-beneficios-de-estudiar-farmacia-y-bioquimica/",
"https://uma.edu.pe/4-julio-quieres-estudiar-nutricion/",
"https://uma.edu.pe/30-junio-crea-tu-producto-y-traspasa-fronteras/",
"https://uma.edu.pe/30-junio-edita-videos-para-tu-negocio-desde-tu-smartphone/",
"https://uma.edu.pe/22-junio-rol-de-los-profesionales-en-salud-publica/",
"https://uma.edu.pe/tecnico-farmaceutico/",
"https://uma.edu.pe/16-junio-disena-tu-logo-en-una-plataforma-digital/",
"https://uma.edu.pe/14-junio-experiencias-exitosas-en-programas-preventivos-del-sector-salud/",
"https://uma.edu.pe/14-junio-crea-tu-producto-y-traspasa-fronteras/",
"https://uma.edu.pe/4-jun-futuras-lineas-de-investigacion-psicosocial-y-academica-post-pandemia/",
"https://uma.edu.pe/convenio-con-la-universidad-catolica-de-uruguay/",
"https://uma.edu.pe/convenio-con-la-universidad-cuauhtemoc-de-aguascalientes-uca/",
"https://uma.edu.pe/convenio-con-la-universidad-de-mujeres-de-texas-twu/",
"https://uma.edu.pe/convenio-con-la-universidad-autonoma-de-aguascalientes-uaa/",
"https://uma.edu.pe/convenio-la-universidad-gran-colombia/",
"https://uma.edu.pe/convenio-con-la-institucion-universitaria-marco-fidel-suarez/",
"https://uma.edu.pe/convenio-con-la-universidad-cooperativa-de-colombia/",
"https://uma.edu.pe/convenio-con-la-universidad-central/",
"https://uma.edu.pe/convenio-la-universidad-autonoma-de-baja-california/",
"https://uma.edu.pe/convenio-con-la-universidad-silva-henriquez/",
"https://uma.edu.pe/convenio-universidad-juarez-autonoma-de-tabasco/",
"https://uma.edu.pe/convenio-la-universidad-autonoma-de-occidente/",
"https://uma.edu.pe/convenio-con-la-fundacion-juan-de-castellanos/",
"https://uma.edu.pe/convenio-el-colegio-mayor-de-antioquia/",
"https://uma.edu.pe/convenio-con-la-universidad-internacional/",
"https://uma.edu.pe/convenio-con-el-consejo-nacional-para-la-acreditacion-en-informatica-y-computacion-de-mexico-conaic/",
"https://uma.edu.pe/convenio-con-la-fundacion-universitaria-ceipa/",
"https://uma.edu.pe/convenio-con-la-universidad-catolica-de-cordoba/",
"https://uma.edu.pe/convenio-la-universidad-del-cauca/",
"https://uma.edu.pe/convenio-con-la-universidad-internacional-del-ecuador-uide/",
"https://uma.edu.pe/convenio-con-la-universidad-autonoma-de-baja-california-del-sur-uabcs/",
"https://uma.edu.pe/convenio-con-la-universidad-nacional-del-salta/",
"https://uma.edu.pe/convenio-con-la-universidad-de-cartagena/",
"https://uma.edu.pe/convenio-con-la-benemerita-universidad-autonoma-de-puebla/",
"https://uma.edu.pe/uma-firma-convenio-con-la-buap-mexico/",
"https://uma.edu.pe/convenio-con-laboratorios-a-c-farma/",
"https://uma.edu.pe/convenio-con-boticas-peru/",
"https://uma.edu.pe/convenio-con-instituto-sise/",
"https://uma.edu.pe/convenio-con-el-ministerio-de-salud-minsa/",
"https://uma.edu.pe/convenio-con-el-hospital-de-huaycan/",
"https://uma.edu.pe/convenio-con-la-diris-centro/",
"https://uma.edu.pe/convenio-con-la-clinica-san-miguel/",
"https://uma.edu.pe/convenio-con-clinica-mundo-salud/",
"https://uma.edu.pe/convenio-con-el-colegio-de-nutricionistas-del-peru-regional-iv/",
"https://uma.edu.pe/convenio-con-la-cooperativa-el-tumi/",
"https://uma.edu.pe/convenio-con-la-cooperativa-de-ahorro-y-credito-hosni/",
"https://uma.edu.pe/convenio-con-la-cooperativa-san-hilarion/",
"https://uma.edu.pe/la-universidad-maria-auxiliadora-uma-y-el-congreso-de-la-republica-organizan-foro-internacional-de-salud/",
"https://uma.edu.pe/convenio-con-la-universidad-catolica-boliviana-san-pablo/",
"https://uma.edu.pe/se-realizo-foro-internacional-de-salud-organizado-por-la-universidad-maria-auxiliadora-y-el-congreso-de-la-republica/",
"https://uma.edu.pe/universidad-maria-auxiliadora-uma-realiza-open-day/",
"https://uma.edu.pe/la-uma-realizara-su-ii-congreso-internacional-de-ciencias-empresariales/",
"https://uma.edu.pe/universidad-maria-auxiliadora-uma-sede-anfitriona-de-las-misiones-academicas-2022-que-reune-a-la-uma-con-la-universidad-cooperativa-de-colombia-ucc-y-la-universidad-del-valle-de-mexico-uvm/",
"https://uma.edu.pe/convenio-con-la-universidad-abierta-interamericana/",
"https://uma.edu.pe/universidad-federal-de-rio-de-janeiro-brasil/",
"https://uma.edu.pe/convenio-con-farmacia-universal/",
"https://uma.edu.pe/convenio-con-sedapal/",
"https://uma.edu.pe/convenio-con-icim/",
"https://uma.edu.pe/80-de-los-directores-y-gerentes-no-saben-como-crear-verdaderas-metas-a-largo-plazo/",
"https://uma.edu.pe/talento-estrategia-y-emprendimiento/",
"https://uma.edu.pe/cuando-el-metaverso-nos-alcance-en-china/",
"https://uma.edu.pe/cuales-son-los-puntos-clave-a-la-hora-de-elaborar-un-proyecto/",
"https://uma.edu.pe/etica-en-los-negocios/",
"https://uma.edu.pe/que-pierde-un-director-o-gerente-general-si-no-crea-escenarios-futuros-validados-matematicamente/",
"https://uma.edu.pe/el-poder-del-feedback-como-herramienta-de-gestion-personal-y-organizacional/",
"https://uma.edu.pe/muerte-prematura-de-las-pymes/",
"https://uma.edu.pe/el-posicionamiento-aplicado-en-la-historia/",
"https://uma.edu.pe/los-negocios-empresariales-y-la-sociedad/",
"https://uma.edu.pe/en-peru-y-en-argentina7-de-cada-10-planes-estrategicos-estan-mal-elaborados-y-no-crean-valor/",
"https://uma.edu.pe/negocios-internacionales-y-marketing/",
"https://uma.edu.pe/porque-debe-ser-bueno-investigar-en-el-campo-de-las-ciencias-contables/",
"https://uma.edu.pe/la-importancia-de-contar-historias-en-marketing/",
"https://uma.edu.pe/las-claves-del-talento-y-del-conocimiento-para-generar-valor-e-innovacion-en-la-organizacion/",
"https://uma.edu.pe/supervisor-de-validaciones-y-calificaciones/",
"https://uma.edu.pe/personal-para-bpa-y-bpdt/",
"https://uma.edu.pe/se-necesita-contadora/",
"https://uma.edu.pe/la-adaptacion-a-nuevos-mercados-y-tecnologias/",
"https://uma.edu.pe/indicadores-de-gestion-global-de-negocios-e-indicadores-de-gestion-de-personas/",
"https://uma.edu.pe/universidad-maria-auxiliadora-impartio-programa-de-formacion-en-emprendimiento-a-escolares/",
"https://uma.edu.pe/conociendo-a-nuestros-colaboradores-una-cultura-empresarial/",
"https://uma.edu.pe/universidad-maria-auxiliadora-suscribe-convenio-con-el-colegio-de-contadores-publicos-de-lima/",
"https://uma.edu.pe/convenio-con-el-colegio-de-contadores-de-lima/",
"https://uma.edu.pe/personal-para-topico-de-salud/",
"https://uma.edu.pe/se-busca-asistente-en-contabilidad-cajero-a-asistente-administrativo/",
"https://uma.edu.pe/se-busca-practicante-administrativo/",
"https://uma.edu.pe/universidad-maria-auxiliadora-lanza-convocatoria-para-fondos-concursables-2023/",
"https://uma.edu.pe/universidad-maria-auxiliadora-realiza-la-jornada-de-investigacion-2022/",
"https://uma.edu.pe/universidad-maria-auxiliadora-firma-convenio-con-el-instituto-carrion/",
"https://uma.edu.pe/convenio-con-el-instituto-carrion/",
"https://uma.edu.pe/18-enero-por-que-estudiar-farmacia-y-bioquimica/",
"https://uma.edu.pe/19-enero-descubriendo-mi-vocacion-en-psicologia/",
"https://uma.edu.pe/17-enero-quieres-ser-nutricionista/",
"https://uma.edu.pe/12-enero-que-debes-saber-antes-de-estudiar-psicologia/",
"https://uma.edu.pe/universidad-maria-auxiliadora-firma-convenio-con-el-colegio-de-licenciados-en-administracion-del-callao/",
"https://uma.edu.pe/convenio-corlad-callao/",
"https://uma.edu.pe/convenio-atic-uma/",
"https://uma.edu.pe/universidad-maria-auxiliadora-entrega-becas-a-sus-estudiantes/",
"https://uma.edu.pe/como-hacer-una-estrategia-de-marketing-digital-exitosa/",
"https://uma.edu.pe/universidad-maria-auxiliadora-suscribe-convenio-con-el-colegio-tecnologo-medico-del-peru/",
"https://uma.edu.pe/universidad-maria-auxiliadora-celebrara-la-semana-del-administrador-en-conjunto-con-el-colegio-de-licenciados-en-administracion-del-callao/",
"https://uma.edu.pe/estudiantes-de-la-universidad-maria-auxiliadora-participan-de-campana-de-salud-organizada-por-la-municipalidad-de-magdalena/",
"https://uma.edu.pe/24-febrero-psicologo-por-un-dia/",
"https://uma.edu.pe/23-febrero-antropometria-para-adultos/",
"https://uma.edu.pe/22-febrero-disena-tu-logo-en-una-plataforma-digital/",
"https://uma.edu.pe/22-febrero-exporta-un-producto-a-un-mercado-internacional/",
"https://uma.edu.pe/la-universidad-maria-auxiliadora-uma-y-el-colegio-de-nutricionistas-del-peru-imparten-capacitacion-a-dirigentes-de-las-ollas-comunes-de-san-juan-de-lurigancho/",
"https://uma.edu.pe/universidad-maria-auxiliadora-firma-convenio-de-cooperacion-interinstitucional-con-la-universidad-autonoma-de-asuncion-paraguay/",
"https://uma.edu.pe/convenio-con-la-universidad-autonoma-de-asuncion-paraguay/",
"https://uma.edu.pe/escuela-de-posgrado-de-la-uma-aperturara-su-periodo-academico-2023-i/",
"https://uma.edu.pe/convenio-colegio-tecnologo-medico-del-peru/",
"https://uma.edu.pe/universidad-maria-auxiliadora-realiza-campana-de-salud-multi-disciplinaria/",
"https://uma.edu.pe/escuela-de-enfermeria-de-la-uma-celebra-ceremonia-de-la-luz/",
"https://uma.edu.pe/reunion-de-rectores-de-universidades-privadas-convocada-por-sunedu-para-evaluar-los-alcances-de-la-ley-31520/",
"https://uma.edu.pe/practicantes-para-laboratorio-farmaceutico/",
"https://uma.edu.pe/convenio-con-la-corporacion-universitaria-minuto-de-dios-colombia/",
"https://uma.edu.pe/convenio-corlad-lima/",
"https://uma.edu.pe/universidad-maria-auxiliadora-uma-firma-convenio-con-el-colegio-regional-de-administradores-de-lima-corlad-lima/",
"https://uma.edu.pe/universidad-maria-auxiliadora-uma-firma-importante-convenio-de-cooperacion-interinstitucional-con-la-universidad-andina-del-cusco/",
"https://uma.edu.pe/convenio-con-la-universidad-andina-del-cusco-uac/",
"https://uma.edu.pe/decano-de-la-universidad-maria-auxiliadora-recibe-reconocimiento-de-parte-del-congreso-de-la-republica/",
"https://uma.edu.pe/director-de-psicologia-de-la-uma-recibe-el-premio-nacional-de-psicologia-2023/",
"https://uma.edu.pe/convenio-con-la-universidad-reina-isabel-i-espana/",
"https://uma.edu.pe/convenio-con-inkafarma/",
"https://uma.edu.pe/convenio-con-mifarma/",
"https://uma.edu.pe/universidad-maria-auxiliadora-uma-firma-convenio-con-las-cadenas-de-farmacias-mas-importantes-del-pais/",
"https://uma.edu.pe/universidad-maria-auxiliadora-uma-realiza-la-final-de-la-copa-uma/",
"https://uma.edu.pe/uma-participa-del-simulacro-nacional-de-sismo/",
"https://uma.edu.pe/programa-academico-de-psicologia-de-la-universidad-maria-auxiliadora-uma-organizo-el-i-psico-debate-2023/",
"https://uma.edu.pe/estudiantes-de-psicologia-de-la-universidad-maria-auxiliadora-uma-realizan-talleres-de-salud-mental-en-colegios-de-san-juan-de-lurigancho/",
"https://uma.edu.pe/universidad-maria-auxiliadora-uma-participo-en-evento-organizado-por-el-congreso-de-la-republica/",
"https://uma.edu.pe/estudiantes-de-enfermeria-de-la-universidad-maria-auxiliadora-participan-en-campana-de-salud-organizada-por-el-ministerio-de-salud/",
"https://uma.edu.pe/estudiantes-de-enfermeria-de-la-universidad-maria-auxiliadora-uma-atienden-a-adultos-mayores-en-estado-de-abandono-en-el-centro-de-lima/",
"https://uma.edu.pe/universidad-maria-auxiliadora-apertura-su-maestria-en-administracion-de-empresas-mba/",
"https://uma.edu.pe/universidad-maria-auxiliadora-uma-realiza-conversatorio-internacional-sobre-emprendimiento/",
"https://uma.edu.pe/carrera-de-administracion-y-marketing-uma-estuvo-presente-en-seminario-internacional-de-universidad-de-cuauhtemoc-mexico/",
"https://uma.edu.pe/carrera-de-administracion-y-negocios-internacionales-de-la-uma-realizo-catedra-abierta-con-universidad-nacional-lomas-de-zamora-argentina/",
"https://uma.edu.pe/estudiantes-destacados-y-docente-de-la-universidad-maria-auxiliadora-uma-participan-en-curso-internacional/",
"https://uma.edu.pe/universidad-san-buenaventura-sede-bogota-dicto-conferencia-a-comunidad-uma-por-el-dia-internacional-del-emprendimiento/",
"https://uma.edu.pe/universidad-maria-auxiliadora-uma-firma-convenio-con-la-municipalidad-metropolitana-de-lima/",
"https://uma.edu.pe/estudiantes-de-la-universidad-maria-auxiliadora-uma-en-movilidad-estudiantil-con-la-universidad-cooperativa-de-colombia-ucc/",
"https://uma.edu.pe/docente-de-la-universidad-maria-auxiliadora-recibe-reconocimiento-por-parte-del-colegio-quimico-farmaceutico-de-lima-cqfdl/",
"https://uma.edu.pe/la-universidad-maria-auxiliadora-uma-participa-de-proyecto-de-responsabilidad-social-en-convenio-con-la-municipalidad-metropolitana-de-lima/",
"https://uma.edu.pe/la-universidad-maria-auxiliadora-uma-y-la-municipalidad-metropolitana-de-lima-realizan-campana-de-arborizacion-en-san-juan-de-lurigancho/",
"https://uma.edu.pe/convenio-con-la-universidad-mariana-colombia/",
"https://uma.edu.pe/convenio-con-la-universidad-de-iberoamerica-unibe-costa-rica/",
"https://uma.edu.pe/convenio-con-la-universidad-internacional-de-las-americas-uia-costa-rica/",
"https://uma.edu.pe/decana-nacional-del-colegio-de-nutricionistas-del-peru-realiza-visita-academica-a-la-universidad-maria-auxiliadora-uma/",
"https://uma.edu.pe/convenio-con-la-universidad-del-sinu-elias-bechara-zainum-colombia/",
"https://uma.edu.pe/uma-firma-convenios-con-universidades-de-costa-rica-y-colombia/",
"https://uma.edu.pe/estudiantes-de-nutricion-y-dietetica-y-psicologia-de-la-universidad-maria-auxiliadora-uma-participaron-de-la-ceremonia-de-investidura-2023-1/",
"https://uma.edu.pe/estudiantes-de-enfermeria-de-la-uma-celebraron-el-dia-turquesa/",
"https://uma.edu.pe/universidad-maria-auxiliadora-uma-imparte-webinar-internacional-con-ceo-de-clear-communication-academy/",
"https://uma.edu.pe/universidad-maria-auxiliadora-uma-firma-convenio-de-cooperacion-con-el-colegio-quimico-farmaceutico-del-callao/",
"https://uma.edu.pe/universidad-maria-auxiliadora-uma-celebra-el-xi-aniversario-de-su-programa-academico-de-farmacia-y-bioquimica/",
"https://uma.edu.pe/universidad-maria-auxiliadora-uma-y-el-colegio-quimico-farmaceutico-del-peru-firman-convenio-de-cooperacion/",
"https://uma.edu.pe/convenio-con-el-colegio-quimico-farmaceutico-del-peru/",
"https://uma.edu.pe/universidad-maria-auxiliadora-uma-se-une-a-la-campana-de-salud-organizada-por-el-club-de-leones/",
"https://uma.edu.pe/la-universidad-maria-auxiliadora-organiza-expoferia-internacional-de-emprendimiento-2023-en-colaboracion-con-universidades-colombianas/",
"https://uma.edu.pe/presentacion/",
"https://uma.edu.pe/cuando-el-duelo-se-transforma-en-un-desafio-para-la-salud-mental/",
"https://uma.edu.pe/psico-uma-en-accion/",
"https://uma.edu.pe/cambiando-historias/",
"https://uma.edu.pe/la-salud-mental-en-tiempos-cambiantes/",
"https://uma.edu.pe/voces-expertas-entrevista-al-dr-eduardo-franco-chalco/",
"https://uma.edu.pe/uma-barrio-responsabilidad-social-universitaria-rsu/",
"https://uma.edu.pe/8-psicotips-para-promover-la-salud-mental/",
"https://uma.edu.pe/convenio-con-la-cooperativa-de-ahorro-y-credito-emphost/",
"https://uma.edu.pe/convenio-con-la-universidad-central-de-bolivia/",
"https://uma.edu.pe/convenio-interinstitucional-con-la-universidad-internacional-del-ecuador-uide/",
"https://uma.edu.pe/convenio-con-la-universidad-nacional-de-la-matanza-argentina/",
"https://uma.edu.pe/universidad-maria-auxiliadora-es-reconocida-por-la-municipalidad-metropolitana-de-lima-por-su-destacada-labor-de-voluntariado/",
"https://uma.edu.pe/convenio-con-la-universidad-tecnologica-de-manzanillo-mexico/",
"https://uma.edu.pe/la-universidad-maria-auxiliadora-y-el-colegio-tecnologo-medico-regional-1-lima-firman-convenio-de-colaboracion/",
"https://uma.edu.pe/convenio-con-el-instituto-sabio-antunez-de-mayolo/",
"https://uma.edu.pe/convenio-con-el-hospital-iii-goyoneche-arequipa/",
"https://uma.edu.pe/indecopi-apertura-curso-virtual-sobre-competencia-desleal/",
"https://uma.edu.pe/plazas-de-empleo-en-la-superintendencia-de-bienes-nacionales-sbn/",
"https://uma.edu.pe/practicas-profesionales-en-la-ugel-04/",
"https://uma.edu.pe/convenio-con-el-colegio-tecnologo-medico-del-peru-regional-i/",
"https://uma.edu.pe/innovacion-y-humor-analizando-la-estrategia-de-apple-en-relajate-es-iphone/",
"https://uma.edu.pe/pymes-peruanas-y-el-reto-de-la-globalizacion/",
"https://uma.edu.pe/conocimiento-del-mercado-internacional-paso-previo-al-exito-comercial/",
"https://uma.edu.pe/ceremonia-de-entrega-de-becas-2024-i/",
"https://uma.edu.pe/la-uma-y-vishwakarma-group-firman-importante-convenio-de-colaboracion-academica-que-marca-el-camino-hacia-futuras-innovaciones/",
"https://uma.edu.pe/la-uma-y-vishwakarma-group-firman-importante-convenio-de-colaboracion-academica-que-marca-el-camino-hacia-futuras-innovaciones-2/",
"https://uma.edu.pe/visita-historica-de-su-excelencia-el-sr-vishvas-sapkal-embajador-de-la-india-para-peru-y-bolivia/",
"https://uma.edu.pe/iv-mision-academica-internacional-entre-texas-womans-university-y-la-uma/",
"https://uma.edu.pe/visita-academica-internacional-asha-saxena-en-la-uma/",
"https://uma.edu.pe/docente-de-la-universidad-maria-auxiliadora-uma-forma-parte-de-publicacion-especial-del-concytec/",
"https://uma.edu.pe/las-implicancias-del-megapuerto-de-chancay-en-el-comercio-internacional-entre-asia-y-america-latina/",
"https://uma.edu.pe/los-beneficios-del-lean-six-sigma-en-la-industria-peruana-un-camino-hacia-la-transformacion/",
"https://uma.edu.pe/yape-en-nuestro-dia-a-dia-una-revolucion-en-pagos-digitales-y-mas/",
"https://uma.edu.pe/la-ingenieria-industrial-motor-del-desarrollo-peruano/",
"https://uma.edu.pe/la-ingenieria-industrial-y-el-desarrollo-de-la-economia-circular-en-el-peru/",
"https://uma.edu.pe/estudiantes-de-provincia-iluminan-la-uma-en-emotiva-ceremonia-de-la-luz/",
"https://uma.edu.pe/postula-y-trabaja-en-la-biblioteca-nacional/",
"https://uma.edu.pe/postula-y-trabaja-en-la-ugel-6/",
"https://uma.edu.pe/postula-al-sernanp/",
"https://uma.edu.pe/la-revolucion-de-la-inteligencia-artificial-impulsando-la-innovacion-en-el-peru/",
"https://uma.edu.pe/beneficios-de-los-almacenes-modernos-un-salto-hacia-el-futuro-de-la-logistica/",
"https://uma.edu.pe/el-litio-un-motor-para-el-desarrollo-economico-y-social-del-peru/",
"https://uma.edu.pe/ingenieria-industrial-y-la-certificacion-iso-9001-la-llave-al-exito-profesional/",
"https://uma.edu.pe/la-agroindustria-peruana-sembrando-un-futuro-de-oportunidades/",
"https://uma.edu.pe/la-revolucion-de-la-gestion-de-proyectos-agilidad-para-el-exito/",
"https://uma.edu.pe/digemid-realiza-feria-informativa-en-la-universidad-maria-auxiliadora/",
"https://uma.edu.pe/el-desafio-del-comercio-exterior-para-el-peru/",
"https://uma.edu.pe/el-gran-cambio-de-la-economia-peruana/",
"https://uma.edu.pe/estudiantes-de-psicologia-de-la-universidad-maria-auxiliadora-exploran-el-fascinante-mundo-del-cerebro-en-el-instituto-nacional-de-ciencias-neurologicas/",
"https://uma.edu.pe/la-uma-se-suma-a-la-campana-de-donacion-voluntaria-de-sangre-del-ministerio-de-salud/",
"https://uma.edu.pe/como-logro-la-india-un-crecimiento-extraordinario-mitos-y-realidades/",
"https://uma.edu.pe/la-universidad-maria-auxiliadora-pionera-en-el-lanzamiento-de-la-carrera-de-ingenieria-de-inteligencia-artificial-en-el-peru-en-el-primer-semestre-2024-i/",
"https://uma.edu.pe/como-la-inteligencia-artificial-esta-revolucionando-la-ciencia-de-la-salud-aplicaciones-y-avances-en-diagnostico-y-tratamiento/",
"https://uma.edu.pe/universidad-maria-auxiliadora-firma-convenio-con-el-colegio-de-enfermeros-regional-iii/",
"https://uma.edu.pe/universidad-maria-auxiliadora-recibe-a-delegacion-de-pasantes-de-vishwakarma-university-india/",
"https://uma.edu.pe/uma-y-asha-saxena-transformando-la-educacion-con-innovacion-en-inteligencia-artificial/",
"https://uma.edu.pe/mujeres-en-color-celebrando-la-creatividad-universitaria/",
"https://uma.edu.pe/convenio-con-el-comando-de-salud-del-ejercito/",
"https://uma.edu.pe/convenio-tripartito-uma-minsa-y-gobierno-regional-de-arequipa/",
"https://uma.edu.pe/la-importancia-de-preparar-a-los-estudiantes-para-el-mercado-laboral-actual/",
"https://uma.edu.pe/la-universidad-maria-auxiliadora-uma-celebra-su-semana-de-responsabilidad-social-y-sostenibilidad-2024/",
"https://uma.edu.pe/convenio-con-el-ist-paul-muller/",
"https://uma.edu.pe/convenio-con-el-instituto-de-capacitacion-profesional-san-agustin-isecap/",
"https://uma.edu.pe/convenio-con-el-club-de-leones-san-juan-bautista-de-san-juan-de-lurigancho/",
"https://uma.edu.pe/feliz-dia-madre-umasina/",
"https://uma.edu.pe/la-universidad-maria-auxiliadora-uma-seleccionada-como-socio-del-proyecto-de-inmersion-global-field-para-harvard-business-school/",
"https://uma.edu.pe/universidad-maria-auxiliadora-uma-selected-as-field-global-immersion-project-partner-for-harvard-business-school/",
"https://uma.edu.pe/la-universidad-maria-auxiliadora-uma-firma-importante-convenio-con-mit-academic-of-engineering-mitaoe-de-pune-india/",
"https://uma.edu.pe/convenio-con-la-mitaoe-india/",
"https://uma.edu.pe/mision-academica-internacional-entre-la-universidad-maria-auxiliadora-y-la-universidad-de-mujeres-de-texas-twu/",
"https://uma.edu.pe/congresista-de-la-republica-realiza-visita-oficial-a-la-uma-para-conocer-la-guarderia-umacitos/",
"https://uma.edu.pe/convenio-con-el-mit-art-design-and-technology-university-mitadt-india/",
"https://uma.edu.pe/convenio-con-bml-munjal-university-india/",
"https://uma.edu.pe/uma-firma-importante-convenio-con-mit-art-design-and-technology-university-mitadt-de-pune-india/",
"https://uma.edu.pe/la-universidad-maria-auxiliadora-firma-un-convenio-de-colaboracion-con-bml-munjal-university-de-india/",
"https://uma.edu.pe/la-universidad-maria-auxiliadora-e-iilm-university-de-india-firman-un-convenio-de-colaboracion/",
"https://uma.edu.pe/escuela-de-farmacia-de-la-uma-realiza-ceremonia-de-investidura/",
"https://uma.edu.pe/uma-celebra-con-exito-la-expoferia-uma-emprende-2024-i/",
"https://uma.edu.pe/uma-realiza-a-la-campana-de-reciclaje-tu-papel-solidario/",
"https://uma.edu.pe/convenio-con-el-iilm-university-de-india/",
"https://uma.edu.pe/convenio-con-la-red-de-salud-de-huarochiri/",
"https://uma.edu.pe/rectora-de-la-uma-realiza-visita-oficial-al-lli-de-singapur/",
"https://uma.edu.pe/uma-firma-convenio-con-avantika-university-en-india/",
"https://uma.edu.pe/convenio-con-avantika-university-india/",
"https://uma.edu.pe/convenio-con-fedcut/",
"https://uma.edu.pe/culmino-con-exito-pasantia-internacional-de-estudiantes-de-ingenieria-de-inteligencia-artificial-y-data-science-de-universidad-de-la-india-en-la-universidad-maria-auxiliadora-uma/",
"https://uma.edu.pe/conversatorio-internacional-experiencias-exitosas-en-salud-publica-reune-a-la-universidad-maria-cano-colombia-y-la-universidad-maria-auxiliadora-peru/",
"https://uma.edu.pe/elementos-culturales-en-campanas-de-marketing-analisis-del-caso-dunkin-peru/",
"https://uma.edu.pe/las-caracteristicas-psicologicas-del-emprendedor-en-san-juan-de-lurigancho-un-reflejo-de-optimismo-y-superacion/",
"https://uma.edu.pe/arranca-con-exito-el-proyecto-universitario-observatorio-de-salud-itinerante-en-aldeas-infantiles-sos-huascar/",
"https://uma.edu.pe/convenio-con-el-instituto-arzobispo-loayza/",
"https://uma.edu.pe/escuela-de-posgrado-de-la-uma-organiza-campana-de-salud-integral-gratuita-en-jicamarca/",
"https://uma.edu.pe/uma-realizo-con-exito-el-iv-congreso-internacional-de-emprendimiento-con-expertos-de-8-paises-latinoamericanos/",
"https://uma.edu.pe/docente-de-la-universidad-maria-auxiliadora-uma-recibe-reconocimiento-por-parte-del-cqfdl/",
"https://uma.edu.pe/universidad-maria-auxiliadora-promueve-la-calidad-academica-y-el-compromiso-social-en-el-dia-nacional-del-adulto-mayor/",
"https://uma.edu.pe/convenio-con-iberonex/",
"https://uma.edu.pe/convenio-con-proa-voluntarios/",
"https://uma.edu.pe/universidad-maria-auxiliadora-recibe-a-docentes-expertas-en-ia-del-mitaoe-india/",
"https://uma.edu.pe/firma-de-convenio-entre-la-universidad-maria-auxiliadora-y-proa-voluntarios-un-paso-adelante-en-la-formacion-integral-de-los-estudiantes/",
"https://uma.edu.pe/universidad-maria-auxiliadora-refuerza-su-compromiso-con-la-sostenibilidad-ambiental-mas-de-500-arboles-plantados-en-san-juan-de-lurigancho/",
"https://uma.edu.pe/universidad-maria-auxiliadora-firma-convenio-de-cooperacion-con-la-universidad-tecmilenio-de-mexico/",
"https://uma.edu.pe/convenio-con-la-universidad-tecmilenio-mexico/",
"https://uma.edu.pe/la-universidad-maria-auxiliadora-presenta-el-proyecto-suma-en-la-jornada-de-sensibilizacion-medioambiental-con-la-participacion-de-serpar-y-alianzas-estrategicas/",
"https://uma.edu.pe/uma-13-anos-cambiando-historias/",
"https://uma.edu.pe/la-importancia-de-la-educacion-virtual/",
"https://uma.edu.pe/rectora-de-la-universidad-maria-auxiliadora-uma-forma-parte-del-consejo-directivo-de-fipes/",
"https://uma.edu.pe/universidad-maria-auxiliadora-fortalece-su-compromiso-con-la-educacion-internacional-recibiendo-a-profesoras-de-la-universidad-mariana-de-colombia/",
"https://uma.edu.pe/estudiantes-de-la-universidad-maria-auxiliadora-clasifican-en-el-dataton-2024-del-ministerio-de-trabajo/",
"https://uma.edu.pe/habilidades-sociales-y-emocionales-para-tener-exito-en-la-vida-profesional-y-personal/",
"https://uma.edu.pe/cientos-de-estudiantes-de-secundaria-visitan-la-universidad-maria-auxiliadora/",
"https://uma.edu.pe/dia-internacional-de-los-voluntarios-municipalidad-de-lima-reconoce-el-trabajo-de-los-voluntarios-de-la-universidad-maria-auxiliadora/",
"https://uma.edu.pe/estudiantes-de-la-universidad-maria-auxiliadora-culminan-su-campo-clinico-en-el-hospital-militar-central/",
"https://uma.edu.pe/la-universidad-maria-auxiliadora-recibe-reconocimiento-de-essalud-por-su-valiosa-contribucion-a-la-salud-publica/",
"https://uma.edu.pe/la-universidad-maria-auxiliadora-refuerza-su-compromiso-con-la-salud-mental-participando-en-la-mesa-de-trabajo-sobre-la-ley-de-salud-mental/",
"https://uma.edu.pe/la-universidad-maria-auxiliadora-promueve-habitos-saludables-con-campana-de-salud-nutricional/",
"https://uma.edu.pe/estudiantes-de-la-uma-participan-en-campana-de-arborizacion-en-villa-maria-del-triunfo-como-parte-del-proyecto-ambiental-suma/",
"https://uma.edu.pe/directivo-del-colegio-de-psicologos-del-peru-realiza-visita-academica-a-la-universidad-maria-auxiliadora-uma/",
"https://uma.edu.pe/una-conferencia-exclusiva-que-amplio-nuestra-vision-sobre-la-vida-saludable-y-la-longevidad/",
"https://uma.edu.pe/el-avance-de-la-robotica-en-la-fisioterapia-disminuye-el-tiempo-de-recuperacion-de-pacientes/",
"https://uma.edu.pe/liderazgo-y-excelencia-en-la-educacion-farmaceutica/",
"https://uma.edu.pe/uma-promueve-habitos-saludables-en-el-dia-mundial-de-la-obesidad/",
"https://uma.edu.pe/facultad-de-farmacia-y-bioquimica-de-la-uma-impulsa-semilleros-de-investigacion/",
"https://uma.edu.pe/simbolo-de-compromiso-y-vocacion-estudiantes-de-la-uma-realizan-ceremonia-de-la-luz/",
"https://uma.edu.pe/el-40-de-las-personas-podria-verse-afectada-por-la-ia-en-las-proximas-decadas/"

]

# Scrape pages and store the results in 'documents'
documents = []
for url in urls:
    text = scrape_page(url)
    if text:
        documents.append(text)

# If no data is scraped, store a placeholder
if not documents:
    documents.append("No data available.")

# Initialize TF-IDF
vectorizer = TfidfVectorizer(stop_words='english')
doc_vectors = vectorizer.fit_transform(documents)

def get_best_doc_and_score(query):
    """
    Given a user query, returns:
      best_doc  : the text of the most similar scraped document
      best_score: the highest similarity score (float)
    """
    query_vec = vectorizer.transform([query])
    similarities = cosine_similarity(query_vec, doc_vectors).flatten()
    best_idx = similarities.argmax()
    best_doc = documents[best_idx]
    best_score = similarities[best_idx]
    return best_doc, best_score

@app.route('/get_response', methods=['POST'])
def get_response():
    """
    Endpoint for the chatbot's POST request.
    Expects JSON with 'query' field.
    Returns the best matching document and its similarity score.
    """
    data = request.get_json()
    query = data.get("query", "")
    best_doc, best_score = get_best_doc_and_score(query)
    return jsonify({
        "best_doc": best_doc,
        "best_score": float(best_score)
    })

if __name__ == '__main__':
    # Grab the PORT environment variable provided by Render, default to 5000 locally
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=True)
